/*
 * Interface translation. English text is the key (gettext style), so every string in the code is
 * readable and a missing translation simply shows English. Catalogs live in ./locales/<code>.json and
 * are generated by scripts/translate_ui.py from the strings extracted out of this codebase.
 *
 * tr() reads module state, so it works everywhere (components, status maps, formatters). Changing the
 * language re-keys the app root (see LanguageRoot), which re-renders every screen in the new language.
 */
import { create } from "zustand";

export type Lang = "en" | "hi" | "ta" | "te" | "kn" | "ml" | "mr" | "bn" | "gu";

export const LANGUAGES: { code: Lang; name: string; native: string; locale: string }[] = [
  { code: "en", name: "English", native: "English", locale: "en-IN" },
  { code: "hi", name: "Hindi", native: "हिन्दी", locale: "hi-IN" },
  { code: "ta", name: "Tamil", native: "தமிழ்", locale: "ta-IN" },
  { code: "te", name: "Telugu", native: "తెలుగు", locale: "te-IN" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", locale: "kn-IN" },
  { code: "ml", name: "Malayalam", native: "മലയാളം", locale: "ml-IN" },
  { code: "mr", name: "Marathi", native: "मराठी", locale: "mr-IN" },
  { code: "bn", name: "Bengali", native: "বাংলা", locale: "bn-IN" },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", locale: "gu-IN" },
];

const loaders = import.meta.glob<{ default: Record<string, string> }>("./locales/*.json");
let catalog: Record<string, string> = {};
let current: Lang = "en";

export function tr(text: string, vars?: Record<string, string | number>): string {
  let out = (current !== "en" && catalog[text]) || text;
  if (vars) out = out.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m));
  return out;
}

/** Marks a string for extraction without translating it (for values that are translated later with t()). */
export const msg = (text: string) => text;

export function locale(): string {
  return LANGUAGES.find((l) => l.code === current)?.locale ?? "en-IN";
}

function stored(): Lang {
  try {
    const v = localStorage.getItem("pramaan.lang") as Lang | null;
    if (v && LANGUAGES.some((l) => l.code === v)) return v;
  } catch {
    /* storage unavailable */
  }
  const nav = (navigator.language || "en").slice(0, 2) as Lang;
  return LANGUAGES.some((l) => l.code === nav) ? nav : "en";
}

async function load(lang: Lang): Promise<void> {
  if (lang === "en") {
    catalog = {};
  } else {
    const loader = loaders[`./locales/${lang}.json`];
    catalog = loader ? (await loader()).default : {};
  }
  current = lang;
  document.documentElement.lang = lang;
}

interface I18nState {
  lang: Lang;
  ready: boolean;
  init: () => Promise<void>;
  setLang: (lang: Lang) => Promise<void>;
}

export const useI18n = create<I18nState>((set) => ({
  lang: "en",
  ready: false,
  async init() {
    const lang = stored();
    await load(lang);
    set({ lang, ready: true });
  },
  async setLang(lang) {
    await load(lang);
    try {
      localStorage.setItem("pramaan.lang", lang);
    } catch {
      /* session only */
    }
    set({ lang });
  },
}));
